In [1]:
import numpy as np


In [2]:
np.random.rand(5,10) # (y, x)

array([[0.97013378, 0.79901418, 0.13881144, 0.17682182, 0.14488403,
        0.05754064, 0.38489881, 0.73206939, 0.27161768, 0.61501749],
       [0.04137396, 0.90949246, 0.50837116, 0.79380703, 0.909977  ,
        0.16275895, 0.92498284, 0.07220186, 0.02423792, 0.9827523 ],
       [0.97381383, 0.88484289, 0.16458046, 0.70251564, 0.05276167,
        0.95826317, 0.03041763, 0.51529081, 0.11170583, 0.56493761],
       [0.17027938, 0.45366296, 0.10076513, 0.56207272, 0.36960199,
        0.95383033, 0.83063748, 0.55565506, 0.90512776, 0.23534351],
       [0.73500013, 0.90863888, 0.66471419, 0.621122  , 0.59568401,
        0.19463718, 0.57442651, 0.51299954, 0.41580558, 0.65855461]])

In [3]:
np.zeros((5,3)) 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
import torch

In [5]:
torch.rand(3,2)

tensor([[ 0.0373,  0.8964],
        [ 0.3493,  0.8558],
        [ 0.2538,  0.0833]])

In [9]:
ma = torch.rand(3,2)
mb = torch.rand(2,3)
torch.matmul(ma,mb)

tensor([[ 0.0648,  0.1735,  0.2877],
        [ 0.0865,  0.1089,  0.2621],
        [ 0.0321,  0.3423,  0.3977]])

- learning from data:  a short course